/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author maik
 */
public class ProdutoView extends JFrame {

    /**
     * Creates new form ProdutoView
     */
    public ProdutoView() {
        initComponents();
        setVisible(true);
    }

    public JButton getButtonAdicionarProduto() {
        return buttonAdicionarProduto;
    }

    public JButton getButtonEditarProduto() {
        return buttonEditarProduto;
    }

    public JButton getButtonListarProdutosNaoOrdenados() {
        return buttonListarProdutosNaoOrdenados;
    }

    public JButton getButtonListarProdutosOrdenados() {
        return buttonListarProdutosOrdenados;
    }

    public JButton getButtonRemoverProduto() {
        return buttonRemoverProduto;
    }

    public JComboBox<String> getComboBoxOpcaoTipoDeProduto() {
        return comboBoxOpcaoTipoDeProduto;
    }

    public JLabel getLabelDataDeValidade() {
        return labelDataDeValidade;
    }

    public JLabel getLabelMarca() {
        return labelMarca;
    }

    public JLabel getLabelModelo() {
        return labelModelo;
    }

    public JLabel getLabelNome() {
        return labelNome;
    }

    public JLabel getLabelPreco() {
        return labelPreco;
    }

    public JLabel getLabelQuantidade() {
        return labelQuantidade;
    }

    public JLabel getLabelTipoDeProduto() {
        return labelTipoDeProduto;
    }

    public JTextArea getTextAreaSaida() {
        return textAreaSaida;
    }

    public JTextField getTextFieldDataDeValidade() {
        return textFieldDataDeValidade;
    }

    public JTextField getTextFieldMarca() {
        return textFieldMarca;
    }

    public JTextField getTextFieldModelo() {
        return textFieldModelo;
    }

    public JTextField getTextFieldNome() {
        return textFieldNome;
    }

    public JTextField getTextFieldPreco() {
        return textFieldPreco;
    }

    public JTextField getTextFieldQuantidade() {
        return textFieldQuantidade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTipoDeProduto = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelPreco = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        labelMarca = new javax.swing.JLabel();
        labelModelo = new javax.swing.JLabel();
        labelDataDeValidade = new javax.swing.JLabel();
        comboBoxOpcaoTipoDeProduto = new javax.swing.JComboBox<>();
        textFieldNome = new javax.swing.JTextField();
        textFieldPreco = new javax.swing.JTextField();
        textFieldQuantidade = new javax.swing.JTextField();
        textFieldMarca = new javax.swing.JTextField();
        textFieldModelo = new javax.swing.JTextField();
        textFieldDataDeValidade = new javax.swing.JTextField();
        buttonAdicionarProduto = new javax.swing.JButton();
        buttonRemoverProduto = new javax.swing.JButton();
        buttonEditarProduto = new javax.swing.JButton();
        buttonListarProdutosOrdenados = new javax.swing.JButton();
        buttonListarProdutosNaoOrdenados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSaida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Produtos");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));

        labelTipoDeProduto.setText("Tipo de Produto:");

        labelNome.setText("Nome:");

        labelPreco.setText("Preço:");

        labelQuantidade.setText("Quantidade:");

        labelMarca.setText("Marca (para Eletrônicos):");

        labelModelo.setText("Modelo (para Eletrônicos):");

        labelDataDeValidade.setText("Data de Validade (para Alimentos):");

        comboBoxOpcaoTipoDeProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimento", "Eletrônico" }));

        textFieldNome.setMinimumSize(new java.awt.Dimension(88, 22));
        textFieldNome.setPreferredSize(new java.awt.Dimension(88, 22));

        textFieldPreco.setMinimumSize(new java.awt.Dimension(88, 22));
        textFieldPreco.setPreferredSize(new java.awt.Dimension(88, 22));

        textFieldQuantidade.setMinimumSize(new java.awt.Dimension(88, 22));
        textFieldQuantidade.setPreferredSize(new java.awt.Dimension(88, 22));

        textFieldMarca.setMinimumSize(new java.awt.Dimension(88, 22));
        textFieldMarca.setPreferredSize(new java.awt.Dimension(88, 22));

        textFieldModelo.setMinimumSize(new java.awt.Dimension(88, 22));
        textFieldModelo.setPreferredSize(new java.awt.Dimension(88, 22));

        textFieldDataDeValidade.setMinimumSize(new java.awt.Dimension(88, 22));
        textFieldDataDeValidade.setPreferredSize(new java.awt.Dimension(88, 22));

        buttonAdicionarProduto.setText("Adicionar Produto");

        buttonRemoverProduto.setText("Remover Produto");

        buttonEditarProduto.setText("Editar Produto");

        buttonListarProdutosOrdenados.setText("Listar Produtos Ordenados");

        buttonListarProdutosNaoOrdenados.setText("Listar Produtos Não Ordenados");

        textAreaSaida.setEditable(false);
        textAreaSaida.setColumns(20);
        textAreaSaida.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        textAreaSaida.setRows(5);
        jScrollPane1.setViewportView(textAreaSaida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAdicionarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemoverProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEditarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonListarProdutosOrdenados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonListarProdutosNaoOrdenados)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDataDeValidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTipoDeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxOpcaoTipoDeProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldDataDeValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoDeProduto)
                    .addComponent(comboBoxOpcaoTipoDeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPreco)
                    .addComponent(textFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidade)
                    .addComponent(textFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMarca)
                    .addComponent(textFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModelo)
                    .addComponent(textFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataDeValidade)
                    .addComponent(textFieldDataDeValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdicionarProduto)
                    .addComponent(buttonRemoverProduto)
                    .addComponent(buttonEditarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonListarProdutosOrdenados)
                    .addComponent(buttonListarProdutosNaoOrdenados))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarProduto;
    private javax.swing.JButton buttonEditarProduto;
    private javax.swing.JButton buttonListarProdutosNaoOrdenados;
    private javax.swing.JButton buttonListarProdutosOrdenados;
    private javax.swing.JButton buttonRemoverProduto;
    private javax.swing.JComboBox<String> comboBoxOpcaoTipoDeProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDataDeValidade;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelTipoDeProduto;
    private javax.swing.JTextArea textAreaSaida;
    private javax.swing.JTextField textFieldDataDeValidade;
    private javax.swing.JTextField textFieldMarca;
    private javax.swing.JTextField textFieldModelo;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldPreco;
    private javax.swing.JTextField textFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
